[package]
name = "app"
version = "0.0.0"
publish = false
license = "MIT"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
